// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exp.Template.Infrastructure.Context;

#nullable disable

namespace exp.Template.Infrastructure.Migrations
{
    [DbContext(typeof(AnimalsFoodContext))]
    [Migration("20241024150811_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Abonament", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataIncepere")
                        .HasColumnType("date")
                        .HasColumnName("data_incepere");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date")
                        .HasColumnName("data_sfarsit");

                    b.Property<int?>("Frecventa")
                        .HasColumnType("int")
                        .HasColumnName("frecventa");

                    b.Property<int?>("IdHrana")
                        .HasColumnType("int")
                        .HasColumnName("id_hrana");

                    b.Property<int?>("IdUtilizator")
                        .HasColumnType("int")
                        .HasColumnName("id_utilizator");

                    b.HasKey("Id")
                        .HasName("PK__Abonamen__3213E83F884FF988");

                    b.HasIndex("IdHrana");

                    b.HasIndex("IdUtilizator");

                    b.ToTable("Abonament", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Animale", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Gen")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gen");

                    b.Property<decimal?>("Greutate")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Specie")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("specie");

                    b.Property<int?>("Varsta")
                        .HasColumnType("int")
                        .HasColumnName("varsta");

                    b.HasKey("Id")
                        .HasName("PK__Animale__3213E83FBCC0A72B");

                    b.ToTable("Animale", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Comandum", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataComenzii")
                        .HasColumnType("date")
                        .HasColumnName("data_comenzii");

                    b.Property<bool?>("Discount")
                        .HasColumnType("bit")
                        .HasColumnName("discount");

                    b.Property<int?>("IdAbonament")
                        .HasColumnType("int")
                        .HasColumnName("id_abonament");

                    b.Property<int?>("IdUtilizator")
                        .HasColumnType("int")
                        .HasColumnName("id_utilizator");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__Comanda__3213E83F93CD6B16");

                    b.HasIndex("IdAbonament");

                    b.HasIndex("IdUtilizator");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("NumarComenzi")
                        .HasColumnType("int")
                        .HasColumnName("numar_comenzi");

                    b.Property<decimal?>("ProcentDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("procent_discount");

                    b.HasKey("Id")
                        .HasName("PK__Discount__3213E83F875390B0");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Hrana", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descriere")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descriere");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nume");

                    b.Property<decimal?>("Pret")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("pret");

                    b.Property<int?>("Stoc")
                        .HasColumnType("int")
                        .HasColumnName("stoc");

                    b.HasKey("Id")
                        .HasName("PK__Hrana__3213E83F9A6F6F52");

                    b.ToTable("Hrana", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Livrari", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AdresaLivrare")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("adresa_livrare");

                    b.Property<DateOnly?>("DataLivrare")
                        .HasColumnType("date")
                        .HasColumnName("data_livrare");

                    b.Property<int?>("IdComanda")
                        .HasColumnType("int")
                        .HasColumnName("id_comanda");

                    b.HasKey("Id")
                        .HasName("PK__Livrari__3213E83F7E257F4F");

                    b.HasIndex("IdComanda");

                    b.ToTable("Livrari", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("MigrationId", "ContextKey")
                        .HasName("PK_dbo.__MigrationHistory");

                    b.ToTable("__MigrationHistory", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nume");

                    b.Property<string>("Parola")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("parola");

                    b.Property<string>("Prenume")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenume");

                    b.HasKey("Id")
                        .HasName("PK__Utilizat__3213E83F5FD05E0A");

                    b.ToTable("Utilizator", (string)null);
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Abonament", b =>
                {
                    b.HasOne("exp.Template.Infrastructure.Entities.Hrana", "IdHranaNavigation")
                        .WithMany("Abonaments")
                        .HasForeignKey("IdHrana")
                        .HasConstraintName("FK__Abonament__id_hr__2D27B809");

                    b.HasOne("exp.Template.Infrastructure.Entities.Utilizator", "IdUtilizatorNavigation")
                        .WithMany("Abonaments")
                        .HasForeignKey("IdUtilizator")
                        .HasConstraintName("FK__Abonament__id_ut__2C3393D0");

                    b.Navigation("IdHranaNavigation");

                    b.Navigation("IdUtilizatorNavigation");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Comandum", b =>
                {
                    b.HasOne("exp.Template.Infrastructure.Entities.Abonament", "IdAbonamentNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdAbonament")
                        .HasConstraintName("FK__Comanda__id_abon__30F848ED");

                    b.HasOne("exp.Template.Infrastructure.Entities.Utilizator", "IdUtilizatorNavigation")
                        .WithMany("Comanda")
                        .HasForeignKey("IdUtilizator")
                        .HasConstraintName("FK__Comanda__id_util__300424B4");

                    b.Navigation("IdAbonamentNavigation");

                    b.Navigation("IdUtilizatorNavigation");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Livrari", b =>
                {
                    b.HasOne("exp.Template.Infrastructure.Entities.Comandum", "IdComandaNavigation")
                        .WithMany("Livraris")
                        .HasForeignKey("IdComanda")
                        .HasConstraintName("FK__Livrari__id_coma__36B12243");

                    b.Navigation("IdComandaNavigation");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Abonament", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Comandum", b =>
                {
                    b.Navigation("Livraris");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Hrana", b =>
                {
                    b.Navigation("Abonaments");
                });

            modelBuilder.Entity("exp.Template.Infrastructure.Entities.Utilizator", b =>
                {
                    b.Navigation("Abonaments");

                    b.Navigation("Comanda");
                });
#pragma warning restore 612, 618
        }
    }
}
